version: "2"

volumes:
  db-data:
    external: false
      
services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app:
    build: .
    env_file: .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -P /tmp/puma.pid
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db